### ISSUE TITLE
How to give crop points

### ISSUE THREAD

**Issue by sowmyakavali** [Moataz-E/computer-vision-lane-finding#1]
`Traceback (most recent call last):
  File "project_4_lane_finding.py", line 516, in <module>
    left_fit = np.polyfit(lefty, leftx, 2)
  File "<__array_function__ internals>", line 6, in polyfit
  File "/home/sowmya/.local/lib/python3.6/site-packages/numpy/lib/polynomial.py", line 601, in polyfit
    raise TypeError("expected non-empty vector for x")
TypeError: expected non-empty vector for x
Segmentation fault (core dumped)
`

I thought the problem is with the PRES_SRC_PNTS .
 How you estimated these points can you explain?

**Comment by Moataz-E** [comment]
Your leftx array is empty, that means no points are being detected. You need to check why that is the case. Might be just one image that is causing this.
